import type { DocNode } from "@/lib/types";
import part01 from "./document-parts/part-01.json";
import part02 from "./document-parts/part-02.json";
import part03 from "./document-parts/part-03.json";
import part04 from "./document-parts/part-04.json";
import part05 from "./document-parts/part-05.json";
import part06 from "./document-parts/part-06.json";
import part07 from "./document-parts/part-07.json";
import part08 from "./document-parts/part-08.json";
import part09 from "./document-parts/part-09.json";
import part10 from "./document-parts/part-10.json";
import part11 from "./document-parts/part-11.json";
import part12 from "./document-parts/part-12.json";
import part13 from "./document-parts/part-13.json";
import part14 from "./document-parts/part-14.json";
import part15 from "./document-parts/part-15.json";
import part16 from "./document-parts/part-16.json";
import part17 from "./document-parts/part-17.json";
import part18 from "./document-parts/part-18.json";
import part19 from "./document-parts/part-19.json";
import part20 from "./document-parts/part-20.json";
import part21 from "./document-parts/part-21.json";
import part22 from "./document-parts/part-22.json";
import part23 from "./document-parts/part-23.json";
import part24 from "./document-parts/part-24.json";
import part25 from "./document-parts/part-25.json";
import part26 from "./document-parts/part-26.json";
import part27 from "./document-parts/part-27.json";
import part28 from "./document-parts/part-28.json";
import part29 from "./document-parts/part-29.json";
import part30 from "./document-parts/part-30.json";
import part31 from "./document-parts/part-31.json";
import part32 from "./document-parts/part-32.json";
import part33 from "./document-parts/part-33.json";
import part34 from "./document-parts/part-34.json";
import part35 from "./document-parts/part-35.json";
import part36 from "./document-parts/part-36.json";

const documentTree = JSON.parse([part01, part02, part03, part04, part05, part06, part07, part08, part09, part10, part11, part12, part13, part14, part15, part16, part17, part18, part19, part20, part21, part22, part23, part24, part25, part26, part27, part28, part29, part30, part31, part32, part33, part34, part35, part36].join("")) as DocNode;

export default documentTree;
